const EventsData = [
  {
    id: "event1",
    name: "Android Fusion",
    posterUrl: "/Events_Page/Android_Fusion/AndroidFusion.jpg",
    description: "Android Fusion was an immersive event that delved into the integration of Android development, Internet of Things (IoT), and Machine Learning (ML). Participants engaged in hands-on sessions, developing Android applications that interfaced with IoT devices and leveraged ML algorithms. The event featured technical speaker sessions from our club's tech experts, providing deep insights into each part of the integration. Attendees also had the opportunity to network with fellow tech enthusiasts, fostering collaborations and exchanging innovative ideas within the tech community.",
    venue: "LC-205",
    date: "2024-05-09",
    startDatetime: "2024-05-09T09:00",
    endDatetime: "2024-05-09T16:20",
  },
  {
    id: "event2",
    name: "DSA Tussle",
    posterUrl: "/Events_Page/DSA_Tussle/DSA_Tussle.jpg",
    description: "DSA Tussle was an exhilarating day of coding brilliance hosted by the Android Club. The event featured mind-bending problem-solving sessions and epic coding showdowns that kept participants on the edge of their seats. It was a showcase of talent and skill in data structures and algorithms (DSA), where coders competed to solve complex problems under time constraints. The event was a huge success, thanks to the incredible participants who made it unforgettable with their enthusiasm and expertise.",
    venue: "AB-420",
    date: "2024-02-22",
    startDatetime: "2024-02-22T11:00",
    endDatetime: "2024-02-22T15:30",
  },
  {
    id: "event3",
    name: "Meet and Greet",
    posterUrl: "/Events_Page/Meet_and_Greet/Meet_and_greet.jpg",
    description: "Meet and Greet: Android Club Edition was a dynamic event held on October 11th, 2023, designed to ignite participants' passion for technology. This 3-hour session brought together tech rookies and coding ninjas alike for an epic exploration of Android and Software Development. Attendees experienced a blend of inspiration, interaction, innovation, and networking, making it a memorable gathering for everyone involved. The event provided a unique platform for participants to engage with fellow tech enthusiasts, share knowledge, and build valuable connections within the tech community.",
    venue: "Auditorium",
    date: "2023-10-11",
    startDatetime: "2023-10-11T09:00",
    endDatetime: "2023-10-11T12:00",
  },
  {
    id: "event4",
    name: "Cultural Craft",
    posterUrl: "/Events_Page/Other_Events/CulturalCraft.jpg",
    description: "Cultural Craft was the ultimate 4-hour development challenge that brought together innovation and cultural exploration. Participants unleashed their coding wizardry in various categories, including software development, game development, poster designing, and video editing. This exciting event was a fusion of culture and technology, encouraging teams of up to four members to showcase their skills, ignite innovation, and push their limits. It was a memorable tech showdown that highlighted the diverse talents and creativity of all participants.",
    venue: "Auditorium",
    date: "2023-07-31",
    startDatetime: "2023-07-31T09:30",
    endDatetime: "2023-07-31T13:30",
  },
  {
    id: "event5",
    name: "Andro Series 2.0",
    posterUrl: "/Events_Page/AndroSeries2/AndroSeries2.jpg",
    description: "Andro-Series 2.0, organized by the Android Club of VIT Bhopal in association with Coding Ninjas, was an exclusive online webinar focused on Android Architecture. The session was led by Abhishek Raj, a Jaguar software engineer and former Samsung SDE, who is also an IIT Dhanbad CS graduate. With a passion for mentoring, Abhishek has guided over 5000 students to date. This free webinar provided participants with in-depth insights into how Android architecture works. Attendees received certificates and ODs for the session held from 10:00 am to 11:40 am, making it an enriching experience to elevate their knowledge and skills in the Android development world.",
    venue: "Online",
    date: "2024-06-27",
    startDatetime: "2023-06-26T10:00",
    endDatetime: "2023-06-26T11:00",
  },
  {
    id: "event6",
    name: "Bug Off",
    posterUrl: "/Events_Page/Bug_Off/Bug Off.jpg",
    startDatetime: "2023-05-15T09:00",
    endDatetime: "2023-05-15T18:30",
  },
  {
    id: "event7",
    name: "Front-End Sprint",
    posterUrl: "/Events_Page/Other_Events/Front_End_Sprint.jpg",
    startDatetime: "2023-04-10T09:45",
    endDatetime: "2023-04-10T14:30",
  },
  {
    id: "event8",
    name: "Andro-Series",
    posterUrl: "",
    startDatetime: "2023-02-11T15:00",
    endDatetime: "2023-02-11T18:30",
  },
  {
    id: "event9",
    name: "App-A-Thon",
    posterUrl: "/Events_Page/App_A_Thon/App_A_Thon.jpg",
    startDatetime: "2022-12-24T08:00",
    endDatetime: "2022-12-28T06:00",
  },
  {
    id: "event10",
    name: "Code-Raid",
    posterUrl: "/Events_Page/Other_Events/Code-Roid.png",
    startDatetime: "2022-04-22T10:00",
    endDatetime: "2022-04-22T12:00",
  },
  {
    id: "event11",
    name: "Android Master",
    posterUrl: "",
    startDatetime: "2022-04-15T17:00",
    endDatetime: "2022-04-15T20:30",
  },
  {
    id: "event12",
    name: "V-Code",
    posterUrl: "/Events_Page/Other_Events/V-Code.png",
    startDatetime: "2019-03-29T11:00",
    endDatetime: "2019-03-29T14:00",
  },
  {
    id: "event13",
    name: "Blind Coding",
    posterUrl: "",
    startDatetime: "2019-12-06T13:30",
    endDatetime: "2019-12-06T16:30",
  },
  {
    id: "event14",
    name: "Workshop-Android Development",
    posterUrl: "",
    startDatetime: "2018-03-16T8:30",
    endDatetime: "2018-03-18T18:00",
  },
];

export default EventsData;
